name: "tinystories-8k"
type: "BPE"
vocab_size: 8192

dataset_config: "configs/datasets/tinystories.yaml"

special_tokens:
  pad: "<pad>"
  eos: "<eos>"
  bos: "<bos>"
  unk: "<unk>"

output_dir: "tokenizers/tinystories-8k"
