name: "tinystories-16k"
type: "BPE"
vocab_size: 16384

dataset_config: "configs/datasets/tinystories.yaml"

special_tokens:
  pad: "<pad>"
  eos: "<eos>"
  bos: "<bos>"
  unk: "<unk>"

output_dir: "tokenizers/tinystories-16k"
tokenized_output_dir: "data/tinystories-16k-tokenized"
num_proc: null  # null = auto (min(8, cpu_count))
num_threads: 16
